//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoProblems {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoProblems.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable problem notifications.
        /// </summary>
        public static string Mod_Description {
            get {
                return ResourceManager.GetString("Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [UPDATED] Added Plaza &amp; Promenades DLC support.
        ///[UPDATED] Add new notifications from several last DLCs.
        ///[NEW] Added ability to hide normal notification, but show major notifications.
        ///[NEW] Added shortcut for toggling notifications visibility.
        ///[UPDATED] Using Harmony instead of old patching system..
        /// </summary>
        public static string Mod_WhatsNewMessage2_0 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable &quot;{0}&quot;.
        /// </summary>
        public static string Setting_DisableProblem {
            get {
                return ResourceManager.GetString("Setting_DisableProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide any.
        /// </summary>
        public static string Setting_HideAny {
            get {
                return ResourceManager.GetString("Setting_HideAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} —  this options just hide any notifications, but buildings behavior is keeped.
        ///{1} —  the same option, but only not major notifications will be hidden.
        ///{2} —  this option change buildings behavior, it prevents adding problem flags to buildings..
        /// </summary>
        public static string Setting_HideDescription {
            get {
                return ResourceManager.GetString("Setting_HideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide normal, but show major.
        /// </summary>
        public static string Setting_HideNormal {
            get {
                return ResourceManager.GetString("Setting_HideNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide option.
        /// </summary>
        public static string Setting_HideType {
            get {
                return ResourceManager.GetString("Setting_HideType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove problem flags.
        /// </summary>
        public static string Setting_Remove {
            get {
                return ResourceManager.GetString("Setting_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toggle visibility.
        /// </summary>
        public static string Setting_ToggleShortcut {
            get {
                return ResourceManager.GetString("Setting_ToggleShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Airport notifications.
        /// </summary>
        public static string Settings_AirportGroup {
            get {
                return ResourceManager.GetString("Settings_AirportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Campus notifications.
        /// </summary>
        public static string Settings_CampusGroup {
            get {
                return ResourceManager.GetString("Settings_CampusGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable all.
        /// </summary>
        public static string Settings_DisableAll {
            get {
                return ResourceManager.GetString("Settings_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable entire group.
        /// </summary>
        public static string Settings_DisableEntireGrope {
            get {
                return ResourceManager.GetString("Settings_DisableEntireGrope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disasters notifications.
        /// </summary>
        public static string Settings_DisastersGroup {
            get {
                return ResourceManager.GetString("Settings_DisastersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable all.
        /// </summary>
        public static string Settings_EnableAll {
            get {
                return ResourceManager.GetString("Settings_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable entire group.
        /// </summary>
        public static string Settings_EnableEntireGrope {
            get {
                return ResourceManager.GetString("Settings_EnableEntireGrope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fishing notifications.
        /// </summary>
        public static string Settings_FishingGroup {
            get {
                return ResourceManager.GetString("Settings_FishingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General notifications.
        /// </summary>
        public static string Settings_GeneralGroup {
            get {
                return ResourceManager.GetString("Settings_GeneralGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Industry notifications.
        /// </summary>
        public static string Settings_IndustryGroup {
            get {
                return ResourceManager.GetString("Settings_IndustryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not connected notifications.
        /// </summary>
        public static string Settings_NotConnectedGroup {
            get {
                return ResourceManager.GetString("Settings_NotConnectedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other notifications.
        /// </summary>
        public static string Settings_OtherGroup {
            get {
                return ResourceManager.GetString("Settings_OtherGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parks notifications.
        /// </summary>
        public static string Settings_ParksGroup {
            get {
                return ResourceManager.GetString("Settings_ParksGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pedestrian area notifications.
        /// </summary>
        public static string Settings_PedestrianGroup {
            get {
                return ResourceManager.GetString("Settings_PedestrianGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сonsumption notifications.
        /// </summary>
        public static string Settings_СonsumptionGroup {
            get {
                return ResourceManager.GetString("Settings_СonsumptionGroup", resourceCulture);
            }
        }
    }
}
